phraseapp:
  project_id: "5c84a0232c3f55de233855a055336395"
  file_format: "angular_translate"
  push:
    sources:
    -
      file: "apps/common/i18n/dicts/<locale_name>.json"
      params:
        file_format: "angular_translate"
  pull:
    targets:
    -
      file: "apps/common/i18n/dicts/<locale_name>.json"
      params:
        file_format: "angular_translate"
