phraseapp:
  project_id: f7bb887b7b6f54b74e080f97af6ae784
  file_format: yml
  push:
    sources:
      -
        file: ./config/locales/<locale_name>.yml
        file_format: yml
  pull:
    targets:
      -
        file: ./config/locales/<locale_name>.yml
        file_format: yml
