phraseapp:
  project_id: "d1c1a23c27eaf103ce42361a767d7ce2"
  file_format: "json"
  push:
    sources:
    -
      file: "apps/common/i18n/dicts/<locale_name>.json"
      params:
        file_format: "nested_json"
        update_translations: true
  pull:
    targets:
    -
      file: "apps/common/i18n/dicts/<locale_name>.json"
      params:
        file_format: "nested_json"
        update_translations: true
